const emojiAliases = {
  'yes': '1f44e',
  'no': '1f44e',
}

const customEmojiRewrites = {
  'bear_trap': 'mouse_trap',
  'trollface': 'japanese_goblin',
  'excited_clap': 'clap',
}
const emojiOverrides = {

  'dmd-a': '🇦',
  'dmd-b': '🇧',
  'dmd-c': '🇨',
  'dmd-d': '🇩',
  'dmd-e': '🇪',
  'dmd-f': '🇫',
  'dmd-g': '🇬',
  'dmd-h': '🇭',
  'dmd-i': '🇮',
  'dmd-j': '🇯',
  'dmd-k': '🇰',
  'dmd-l': '🇱',
  'dmd-m': '🇲',
  'dmd-n': '🇳',
  'dmd-o': '🇴',
  'dmd-p': '🇵',
  'dmd-q': '🇶',
  'dmd-r': '🇷',
  'dmd-s': '🇸',
  'dmd-t': '🇹',
  'dmd-u': '🇺',
  'dmd-v': '🇻',
  'dmd-w': '🇼',
  'dmd-x': '🇽',
  'dmd-y': '🇾',
  'dmd-z': '🇿',
  'dancing-rgb-letter-a': '🇦',
  'dancing-rgb-letter-b': '🇧',
  'dancing-rgb-letter-c': '🇨',
  'dancing-rgb-letter-d': '🇩',
  'dancing-rgb-letter-e': '🇪',
  'dancing-rgb-letter-f': '🇫',
  'dancing-rgb-letter-g': '🇬',
  'dancing-rgb-letter-h': '🇭',
  'dancing-rgb-letter-i': '🇮',
  'dancing-rgb-letter-j': '🇯',
  'dancing-rgb-letter-k': '🇰',
  'dancing-rgb-letter-l': '🇱',
  'dancing-rgb-letter-m': '🇲',
  'dancing-rgb-letter-n': '🇳',
  'dancing-rgb-letter-o': '🇴',
  'dancing-rgb-letter-p': '🇵',
  'dancing-rgb-letter-q': '🇶',
  'dancing-rgb-letter-r': '🇷',
  'dancing-rgb-letter-s': '🇸',
  'dancing-rgb-letter-t': '🇹',
  'dancing-rgb-letter-u': '🇺',
  'dancing-rgb-letter-v': '🇻',
  'dancing-rgb-letter-w': '🇼',
  'dancing-rgb-letter-x': '🇽',
  'dancing-rgb-letter-y': '🇾',
  'dancing-rgb-letter-z': '🇿',
}

module.exports = {
  emojiAliases,
  emojiOverrides,
  customEmojiRewrites,
}